---
- name: Configura DVD
  hosts: all
  become: no
  tasks:


    - name: Add repository
      yum:
        state: absent
        name: epel-release

    - name: Add key
      rpm_key:
        state: present
        key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-8

    - name: Add repository
      yum:
        state: present
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
            
    - name: Add user curso with a password
      user:
        name: curso
        password: "{{ 'curso' | password_hash('sha512') }}"
        update_password: on_create
        
    - name: Add user curso and generate for them an SSH key
      user:
        name: curso
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: /home/curso/.ssh/id_rsa
      when: inventory_hostname == "servera"
      
    - name: Crear etc hosts
      blockinfile:
        path: /etc/hosts
        block: |
          172.25.0.178 servera.lab.example.com servera
          172.25.0.179 serverb.lab.example.com serverb
          172.25.0.180 serverc.lab.example.com serverc
          172.25.0.181 serverd.lab.example.com serverd
      when: inventory_hostname == "servera"
     
    - name: Change hostname
      hostname: 
        name: "{{ inventory_hostname }}"

    - name: sudo without password for curso user
      copy:
        content: 'curso ALL=(ALL:ALL) NOPASSWD:ALL'
        dest: /etc/sudoers.d/curso_nopasswd
        mode: 0440


    - name: Set authorized key taken from file
      authorized_key:
        user: curso
        state: present
        key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCvJBOcC6h1QcOzgKuWDt0+p6FCUctIHznLJ0eGbsbU6zXvfDEnGr9fFU7JOeYd5i1WLytlMaBRBsUTZcK9oJew9rhLRQfThJtk7to9LuEpVGSlAOHCYE1uAzPWxGkJOt5J7Pe2CPZBMHF9sD3nZZ4N5Z1lYGUaeiV1MTBR5BNHKqF+ZQHm4PR2v/cXQ8JhQUtQJ6JAdYRFEusw36GZ6ZYDE3X2YvZGPBhlV9xtIigukjYFyVayJ3IHxJMZZNgjrGgXoPeIPOOwEzuTF0OkdBz81xRdu2KDSVU8XPxK7hI5GuGJ+AtDwYpuDnjjVwzQ5/sASicVIS48+IDXFWWvduwF ansible-generated on localhost.localdomain"    
