---
    - name: Update db servers
      hosts: dbservers
 
      tasks:
        - name: Lastest postgresql package installed
          yum:
            name:
              - postgresql
              - httpd
            state: latest
          notify:
            - Restart httpd
          changed_when: true
 
      handlers:
        - name: Restart httpd
          service:
            name: httpd
            enabled: yes
            state: restarted
