---
- hosts: dbservers
  tasks:
    - service:
        name: httpd
        enabled: no
        state: stopped
    - yum:
        name: 
          - postgresql
          - httpd     
        state: absent
